baseURL = "http://alexsm.com/"
languageCode = "en-us"
title = "alexsm"
theme = "mainroad"
disqusShortname = "alexsm"

[permalinks]
  post = "/:slug/"

[Params]
  subtitle = "A blog by Oleksandr Semeniuta" 
  description = "Technical blog by Oleksandr Semeniuta: C++, Python, Linux, macOS, programming, build tutorials" 
  copyright = "Oleksandr Semeniuta"
  menu = ["main", "sidebar"]

[Params.sidebar]
  home = "right"
  widgets = ["feed", "sidemenu", "taglist", "recent", "social"]
  single = true

[Params.widgets.social]
  github = "semeniuta"
  linkedin = "semeniuta"
  twitter = "OSemeniuta"
  instagram = "oleksandr_s"
  
  


