baseURL = "http://alexsm.com/"
languageCode = "en-us"
title = "Oleksandr Semeniuta"
theme = "alexsm-theme"
disqusShortname = "alexsm"

[permalinks]
  post = "/:slug/"

[Params]
  subtitle = "A technical blog"
  copyright = "Oleksandr Semeniuta"

[markup]
  [markup.highlight]
    style = 'monokai'
