baseURL = "http://alexsm.com/"
languageCode = "en-us"
title = "alexsm@home"
theme = "alexsm-theme"
disqusShortname = "alexsm"

[permalinks]
  post = "/:slug/"

[Params]
  subtitle = "A technical blog by Oleksandr Semeniuta"
  copyright = "Oleksandr Semeniuta"
  description = "Technical blog by Oleksandr Semeniuta: C++, Python, Linux, macOS, programming, automation with shell scripts"

[markup]
  [markup.highlight]
    style = 'monokai'
